### PR TITLE
Added Sieve Prime

### PR DESCRIPTION
**Pull request by vitouphy**
Some prime number function

### CODE REVIEW

**Comment by invisal** [comment]
For the prime number, you don't need to check from 2 to n - 1. You only need to check from 2 to sqrt(n). You can change your is_prime loop to

```
for (var i = 2; i * i <= n; i++) {
```
For function name. We should change from `sieve_prime` to `sieve_of_eranthoses` to keep the true name of the real algorithm.

**Comment by invisal** [comment]
I have made several benchmark to see whether `sqrt(n)` or `i * i` is faster. It turns out that `sqrt(n)` is slightly faster for larger n, while `i * i` is faster for lower n.

https://jsperf.com/is-prime-implementation-comparison/
https://jsperf.com/is-prime-implementation-comparison-2

You can also slightly improve instead of skipping by 1, we can skip by 2. Since we know that except prime number 2, other prime number are odd number.

Interestingly, we can even increase the speed even further by skip by 6. Because we know that all the prime number must be in the form of 6n + 1 or 6n - 1 except 2 and 3.

**Comment by invisal** [comment]
Another interesting optimization for sieve of eranthoses is to use
```javascript
new Array(n).fill(true);
```

https://jsperf.com/array-fill-vs-array-push/1

**Comment by vitouphy** [comment]
I've improved Sieve of Eratosthenes using that array fill. I just got the concept of skipping by 6 and implemented it using sqrt btw. It improves quite a lot. 
[https://jsperf.com/brute-force-primal-testing](https://jsperf.com/brute-force-primal-testing)

**Pull request merged**
